#!/usr/bin/env python3
"""cuBLAS substitution: the library optimize move's code generator.

Takes one benchmark C file whose hot function is a square row-major GEMM
(C = A * B, all n x n, contiguous) and emits a single self-contained .cu in
which that function's body is replaced by a cublasSgemm/cublasDgemm call --
the rest of the program (init, checksum, timing, I/O) passes through
untouched, so the golden diff still applies. Row-major is handled by the
standard column-major identity C^T = B^T * A^T: swap the operand order, no
transposes, no data movement.

Driven by the "blas" metadata of a scop_targets.json entry (see
agent_pipeline/compiler_moves.run_library_move), or directly:

    ./cublas_to_cu.py benchmark/easy/dense-linalg/gemm.c -o gemm_cublas.cu \
        --fn gemm --type float --dim n

Compile the output with `nvcc ... -lcublas`. Deliberately narrow: exactly the
square row-major GEMM shape, nothing else -- a wrong match fails the caller's
mechanical diff gate rather than shipping wrong code.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from ppcg_to_cu import CXX_PRELUDE, _find_function, die

BLAS_INCLUDES = """\
#include <cuda_runtime.h>
#include <cublas_v2.h>
"""

# gemm() is typically called once per program here, but a static handle keeps
# repeated calls (e.g. a blocked sweep) from re-paying cublasCreate each time.
BODY_TEMPLATE = """{{
    /* cuBLAS substitution (library optimize move, cublas_to_cu.py).
       Row-major C = A*B via the column-major identity C^T = B^T * A^T. */
    static cublasHandle_t ppcg_cublas_handle = NULL;
    if (!ppcg_cublas_handle) cublasCreate(&ppcg_cublas_handle);
    {ctype} *dev_a, *dev_b, *dev_c;
    size_t ppcg_bytes = (size_t)({dim}) * ({dim}) * sizeof({ctype});
    cudaMalloc((void **)&dev_a, ppcg_bytes);
    cudaMalloc((void **)&dev_b, ppcg_bytes);
    cudaMalloc((void **)&dev_c, ppcg_bytes);
    cudaMemcpy(dev_a, {A}, ppcg_bytes, cudaMemcpyHostToDevice);
    cudaMemcpy(dev_b, {B}, ppcg_bytes, cudaMemcpyHostToDevice);
    const {ctype} ppcg_alpha = 1, ppcg_beta = 0;
    {gemm}(ppcg_cublas_handle, CUBLAS_OP_N, CUBLAS_OP_N,
        {dim}, {dim}, {dim}, &ppcg_alpha,
        dev_b, {dim}, dev_a, {dim}, &ppcg_beta, dev_c, {dim});
    cudaMemcpy({C}, dev_c, ppcg_bytes, cudaMemcpyDeviceToHost);
    cudaFree(dev_a); cudaFree(dev_b); cudaFree(dev_c);
}}"""

GEMM_BY_TYPE = {"float": "cublasSgemm", "double": "cublasDgemm"}


def substitute(src, fn, ctype, dim, a, b, c):
    m, open_brace, close_brace = _find_function(src, fn)
    body = BODY_TEMPLATE.format(ctype=ctype, dim=dim, A=a, B=b, C=c,
                                gemm=GEMM_BY_TYPE[ctype])
    return src[:open_brace] + body + src[close_brace + 1:]


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("input", help="benchmark C source")
    ap.add_argument("-o", "--output", required=True, help="output .cu")
    ap.add_argument("--fn", required=True, help="the square-GEMM hot function")
    ap.add_argument("--type", default="float", choices=sorted(GEMM_BY_TYPE),
                    help="element type (default float)")
    ap.add_argument("--dim", default="n",
                    help="the square dimension expression in scope (default n)")
    ap.add_argument("--A", default="A", help="A operand param name")
    ap.add_argument("--B", default="B", help="B operand param name")
    ap.add_argument("--C", default="C", help="C result param name")
    args = ap.parse_args()

    if not os.path.isfile(args.input):
        die("no such file: %s" % args.input)
    with open(args.input) as f:
        src = f.read()
    merged = CXX_PRELUDE + BLAS_INCLUDES + "\n" + substitute(
        src, args.fn, args.type, args.dim, args.A, args.B, args.C)
    header = ("/* Generated by the library optimize move (cuBLAS "
              "substitution) from %s: %s() -> %s. Link with -lcublas. */\n"
              % (os.path.basename(args.input), args.fn,
                 GEMM_BY_TYPE[args.type]))
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write(header + merged)
    print(args.output)


if __name__ == "__main__":
    main()
